sudo: false
env:
- BROWSER_PATH=/home/travis/build/tenbits/selenium-query/chrome-linux/chrome

before_install:
    
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- curl -Lo chrome.zip https://download-chromium.appspot.com/dl/Linux_x64 && unzip chrome.zip
- curl -Lo chromedriver.zip http://chromedriver.storage.googleapis.com/2.16/chromedriver_linux64.zip && unzip chromedriver.zip

before_script:
  
script:
  - "npm test"

language: node_js