sudo: true

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
      
before_install:
    
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- curl -Lo chromedriver.zip http://chromedriver.storage.googleapis.com/2.16/chromedriver_linux64.zip && unzip chromedriver.zip

before_script:
  
script:
  - "npm test"

language: node_js
node_js:
  - "6.6.0"
