sudo: false
dist: trusty
addons:
  apt:
    packages:
      - google-chrome-stable

before_script:
  - export DISPLAY=:99.0
  - curl -Lo chromedriver.zip http://chromedriver.storage.googleapis.com/2.30/chromedriver_linux64.zip && unzip chromedriver.zip
  - sh -e /etc/init.d/xvfb start &
  - sleep 3
  
script:
  - 'npm test'

language: node_js
node_js:
  - "6.6.0"
