sudo: false
before_script:
  - npm install bower
  - bower install
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start  
  - npm run build
  - node_modules/.bin/atma server &
  - sleep 5
  - firefox http://localhost:5777/utest/ &
  - sleep 6

script:
  - "npm test"

language: node_js