os: linux
sudo: required
env: DISPLAY=':99.0'
dist: trusty
addons:
  chrome: stable
  apt:
    update: true
    packages:
      - chromium-chromedriver

before_script:
  - sh -e /etc/init.d/xvfb start
  - google-chrome --version
  - which google-chrome
  - ln --symbolic /usr/lib/chromium-browser/chromedriver "${HOME}/bin/chromedriver"
  #- curl -Lo chromedriver.zip http://chromedriver.storage.googleapis.com/93.0.4577.63/chromedriver_linux64.zip
  #- unzip chromedriver.zip
  - sleep 3

script:
  - npm test

language: node_js

node_js:
  - 16
