sudo: required

dist: trusty

addons:
  chrome: stable

services:
  - xvfb

before_script:
  - export DISPLAY=:99.0
  - curl -Lo chromedriver.zip http://chromedriver.storage.googleapis.com/93.0.4577.63/chromedriver_linux64.zip && unzip chromedriver.zip
  - sleep 3

script:
  - npm test

language: node_js

node_js:
  - 16
